- hosts: all
  sudo: yes

  roles:
    - ansible-oracle-java
    - elasticsearch

  vars:
    java_version: 8
    es_etc:
      cloud.aws.region: "{{ region }}"
      cluster_name: search_cluster
      discovery.type: ec2
      discovery.ec2.groups: elasticsearch-sg
